# Generated by Django 5.2.5 on 2025-10-24 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("resume", "Resume Uploaded"),
                            ("aptitude", "Aptitude"),
                            ("coding", "Coding"),
                            ("tech", "Tech Interview"),
                            ("hr", "HR Interview"),
                            ("done", "Completed"),
                        ],
                        default="resume",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                            ("shortlisted", "Shortlisted"),
                            ("offered", "Offered"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
