# Generated by Django 5.2.7 on 2025-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="resume_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
