# Generated by Django 5.2.7 on 2025-10-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_candidateprofile_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="parsed_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
