# Generated by Django 5.2.7 on 2025-10-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_candidateprofile_parsed_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateprofile",
            name="parsed_data",
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="projects",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
