# Generated by Django 5.2.7 on 2025-10-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_candidateprofile_parsed_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="violations",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
