# Generated by Django 5.2.7 on 2025-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assess", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("options", models.JSONField()),
                ("correct_index", models.IntegerField()),
                ("difficulty", models.CharField(default="medium", max_length=16)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
