# Generated by Django 5.2.7 on 2025-10-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assess", "0002_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("starter_code", models.TextField(blank=True)),
                ("test_cases", models.JSONField(default=list)),
                ("skill_tags", models.JSONField(default=list)),
                ("difficulty", models.CharField(default="medium", max_length=16)),
            ],
        ),
    ]
