# Generated by Django 5.2.7 on 2025-10-25 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assess", "0003_codingquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsubmission",
            name="answers",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="testsubmission",
            name="test_type",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="testsubmission",
            unique_together={("candidate", "test_type")},
        ),
    ]
